import type { ProcessedStock, VerdictType } from '../model/types/stock';

const MOCK_STOCKS: Omit<ProcessedStock, 'lastUpdated'>[] = [
  {
    ticker: 'ADM',
    name: 'Archer-Daniels-Midland',
    sector: 'Consumer Staples',
    strategy: 'Value',
    price: 71.80,
    change: 0.45,
    changePercent: 0.63,
    buyTarget: 70.50,
    stop: 69.50,
    floor: 63.80,
    verdict: 'BUY: Near SMA 50. Strong buyers at 70.50.',
    verdictType: 'BUY',
    notifyEnabled: true,
    indicators: { sma50: 71.10, sma200: 68.40, rsi14: 52.3, atr14: 1.20, smaProximityPct: 0.99 },
    wick: { lowerWick: 1.85, upperWick: 0.42, hasAggressiveBuySignal: true },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: true, hasDoubleTop: false, patternLevel: 70.50, patternDescription: 'Double Bottom at 70.50 – confirmed buyers zone' },
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'Technology',
    strategy: 'Momentum',
    price: 183.04,
    change: -2.14,
    changePercent: -1.16,
    buyTarget: 176.00,
    stop: 170.00,
    floor: 158.00,
    verdict: 'WAIT: Overextended. High risk before GTC.',
    verdictType: 'WAIT',
    notifyEnabled: false,
    indicators: { sma50: 161.80, sma200: 148.20, rsi14: 74.1, atr14: 5.80, smaProximityPct: 13.1 },
    wick: { lowerWick: 0.92, upperWick: 2.40, hasAggressiveBuySignal: false },
    audit: { isOverbought: true, isOverextended: true, isWeakMomentum: false, warnings: ['RSI > 70 — Overbought', 'Price >12% above SMA50 — Overextended'] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
  {
    ticker: 'GE',
    name: 'GE Aerospace',
    sector: 'Industrials',
    strategy: 'Growth',
    price: 304.72,
    change: -5.20,
    changePercent: -1.68,
    buyTarget: 290.00,
    stop: 298.00,
    floor: 280.00,
    verdict: 'AVOID: Trend broken. No buyers detected.',
    verdictType: 'AVOID',
    notifyEnabled: true,
    indicators: { sma50: 318.40, sma200: 295.10, rsi14: 38.2, atr14: 7.40, smaProximityPct: -4.30 },
    wick: { lowerWick: 0.55, upperWick: 3.80, hasAggressiveBuySignal: false },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: true, warnings: ['Volume < 5-day avg — Weak Momentum'] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: true, patternLevel: 310.00, patternDescription: 'Double Top at 310.00 — distribution pattern' },
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'Technology',
    strategy: 'Growth',
    price: 303.73,
    change: 1.88,
    changePercent: 0.62,
    buyTarget: 298.50,
    stop: 295.00,
    floor: 285.00,
    verdict: 'ACCUMULATE: Solid Double Bottom support.',
    verdictType: 'ACCUMULATE',
    notifyEnabled: false,
    indicators: { sma50: 299.20, sma200: 278.80, rsi14: 58.7, atr14: 6.10, smaProximityPct: 1.51 },
    wick: { lowerWick: 2.10, upperWick: 0.80, hasAggressiveBuySignal: true },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: true, hasDoubleTop: false, patternLevel: 295.00, patternDescription: 'Double Bottom at 295.00 — strong structural floor' },
  },
  {
    ticker: 'INTC',
    name: 'Intel Corporation',
    sector: 'Technology',
    strategy: 'Value',
    price: 45.52,
    change: -1.20,
    changePercent: -2.57,
    buyTarget: 42.30,
    stop: 44.00,
    floor: 39.50,
    verdict: 'DANGER: Falling knife. Watch the floor.',
    verdictType: 'DANGER',
    notifyEnabled: true,
    indicators: { sma50: 48.90, sma200: 52.30, rsi14: 28.4, atr14: 1.50, smaProximityPct: -6.92 },
    wick: { lowerWick: 0.28, upperWick: 1.95, hasAggressiveBuySignal: false },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: true, warnings: ['Volume < 5-day avg — Weak Momentum', 'Below SMA50 and SMA200 — Bearish trend'] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    sector: 'Technology',
    strategy: 'Growth',
    price: 415.30,
    change: 3.22,
    changePercent: 0.78,
    buyTarget: 408.00,
    stop: 400.00,
    floor: 385.00,
    verdict: 'BUY: Tight coil above SMA50. Volume confirming.',
    verdictType: 'BUY',
    notifyEnabled: false,
    indicators: { sma50: 410.50, sma200: 388.40, rsi14: 61.2, atr14: 8.20, smaProximityPct: 1.17 },
    wick: { lowerWick: 3.10, upperWick: 1.05, hasAggressiveBuySignal: true },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
  {
    ticker: 'JPM',
    name: 'JPMorgan Chase',
    sector: 'Financials',
    strategy: 'Dividend',
    price: 218.45,
    change: -0.85,
    changePercent: -0.39,
    buyTarget: 213.00,
    stop: 209.50,
    floor: 198.00,
    verdict: 'ACCUMULATE: Pullback to SMA50. Dividend support.',
    verdictType: 'ACCUMULATE',
    notifyEnabled: true,
    indicators: { sma50: 214.20, sma200: 200.30, rsi14: 55.8, atr14: 4.30, smaProximityPct: 2.00 },
    wick: { lowerWick: 1.60, upperWick: 0.70, hasAggressiveBuySignal: false },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: true, hasDoubleTop: false, patternLevel: 210.00, patternDescription: 'Double Bottom at 210.00 — strong buyers zone' },
  },
  {
    ticker: 'XOM',
    name: 'Exxon Mobil',
    sector: 'Energy',
    strategy: 'Dividend',
    price: 108.20,
    change: 1.10,
    changePercent: 1.03,
    buyTarget: 105.50,
    stop: 103.00,
    floor: 97.00,
    verdict: 'BUY: Energy recovery play. Wick confirms buyers.',
    verdictType: 'BUY',
    notifyEnabled: false,
    indicators: { sma50: 106.80, sma200: 103.20, rsi14: 59.4, atr14: 2.10, smaProximityPct: 1.31 },
    wick: { lowerWick: 2.85, upperWick: 0.40, hasAggressiveBuySignal: true },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
  {
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    sector: 'Consumer Discretionary',
    strategy: 'Momentum',
    price: 242.80,
    change: -8.40,
    changePercent: -3.34,
    buyTarget: 225.00,
    stop: 235.00,
    floor: 210.00,
    verdict: 'WAIT: Volatile. Wait for floor confirmation.',
    verdictType: 'WAIT',
    notifyEnabled: false,
    indicators: { sma50: 228.40, sma200: 215.80, rsi14: 48.1, atr14: 12.50, smaProximityPct: 6.29 },
    wick: { lowerWick: 4.20, upperWick: 6.80, hasAggressiveBuySignal: false },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: true, warnings: ['Volume < 5-day avg — Weak Momentum'] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
  {
    ticker: 'META',
    name: 'Meta Platforms',
    sector: 'Technology',
    strategy: 'Growth',
    price: 558.90,
    change: 4.75,
    changePercent: 0.86,
    buyTarget: 545.00,
    stop: 535.00,
    floor: 510.00,
    verdict: 'ACCUMULATE: AI spend justified. Near breakout.',
    verdictType: 'ACCUMULATE',
    notifyEnabled: false,
    indicators: { sma50: 548.20, sma200: 498.40, rsi14: 64.3, atr14: 14.20, smaProximityPct: 1.95 },
    wick: { lowerWick: 2.90, upperWick: 1.40, hasAggressiveBuySignal: false },
    audit: { isOverbought: false, isOverextended: false, isWeakMomentum: false, warnings: [] },
    pattern: { hasDoubleBottom: false, hasDoubleTop: false, patternLevel: null, patternDescription: null },
  },
];

/** Adds random micro-noise to simulate live price updates */
function jitterPrice(base: number, volatility = 0.003): number {
  const noise = (Math.random() - 0.5) * 2 * volatility;
  return parseFloat((base * (1 + noise)).toFixed(2));
}

export function getMockStocks(): ProcessedStock[] {
  return MOCK_STOCKS.map((s) => ({
    ...s,
    price: jitterPrice(s.price),
    lastUpdated: new Date().toISOString(),
  }));
}

export function getMockStockUpdate(ticker: string): ProcessedStock | undefined {
  const base = MOCK_STOCKS.find((s) => s.ticker === ticker);
  if (!base) return undefined;
  const newPrice = jitterPrice(base.price);
  const newChange = parseFloat((newPrice - base.price + base.change).toFixed(2));
  const newChangePct = parseFloat(((newChange / base.price) * 100).toFixed(2));
  return {
    ...base,
    price: newPrice,
    change: newChange,
    changePercent: newChangePct,
    lastUpdated: new Date().toISOString(),
  };
}

export const ALL_SECTORS = [...new Set(MOCK_STOCKS.map((s) => s.sector))].sort();
export const ALL_STRATEGIES = [...new Set(MOCK_STOCKS.map((s) => s.strategy))].sort();
export const ALL_VERDICTS: VerdictType[] = ['BUY', 'ACCUMULATE', 'WAIT', 'AVOID', 'DANGER'];
